server:
  port: 9000
  
spring:
   profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


---

spring:
  profiles: dev
  application:
      name:SpringBootProject
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa: 
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: update
      show-sql: true
      
           
---
      
spring:
  profiles: prod
  application:
     name:SpringBootProject
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb-prod
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    show-sql: true

---
      
 spring:
    profiles: qa
    application:
       name:SpringBootProject
    datasource:
      url: jdbc:mysql://localhost:3306/springbootdb-qa
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    jpa: 
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: update
      show-sql: true
      



